# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

    
stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        

        steps:


            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: 'Azure subscription 1(d94b0629-8c8b-4f9b-8c4a-acb638e36ad4)'
                subscriptionId: ${env:SUBID}
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'Alexcd83RG2020'
                location: 'West US 2'
                templateLocation: 'URL of the file'
                csmFileLink: 'https://raw.githubusercontent.com/Alexcd83/ARMTempl/main/template.json'
                deploymentMode: 'Complete'
                deploymentName: 'LogicAppARMGIT'
                addSpnToEnvironment: true
 steps:
  - script: echo test
    name: ScriptName

  - task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host '##vso[task.setvariable variable=xxx;isOutput=true;]xxx'
  name: PSName
